[package]
name = "dn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-client = "0.20"

shellexpand = "2.1"

arc-swap = "1.5"
tokio = "1.15"
rayon = "1.5"
dotenv = "0.15"
